required-players: 1
countdown-seconds: 15
lobby-spawn:
  world: 'world'
  x: 0.0
  y: 0.0
  z: 0.0
  yaw: -180
  pitch: 0
arenas:
  0:
    world: 'world'
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: -180
    pitch: 0